//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verify_NET.VerifyWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://verifyWS.streetmaster/", ConfigurationName="VerifyWS.Verify")]
    public interface Verify {
        
        // CODEGEN: Il parametro 'TotOutVerify' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://verifyWS.streetmaster/Verify/VerifyRequest", ReplyAction="http://verifyWS.streetmaster/Verify/VerifyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="TotOutVerify")]
        Verify_NET.VerifyWS.VerifyResponse Verify(Verify_NET.VerifyWS.VerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://verifyWS.streetmaster/Verify/VerifyRequest", ReplyAction="http://verifyWS.streetmaster/Verify/VerifyResponse")]
        System.Threading.Tasks.Task<Verify_NET.VerifyWS.VerifyResponse> VerifyAsync(Verify_NET.VerifyWS.VerifyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://verifyWS.streetmaster/")]
    public partial class inputCommon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string capField;
        
        private string civicoField;
        
        private string dugField;
        
        private string indirizzoField;
        
        private string localitaField;
        
        private string localita2Field;
        
        private string provinciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string civico {
            get {
                return this.civicoField;
            }
            set {
                this.civicoField = value;
                this.RaisePropertyChanged("civico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dug {
            get {
                return this.dugField;
            }
            set {
                this.dugField = value;
                this.RaisePropertyChanged("dug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string localita {
            get {
                return this.localitaField;
            }
            set {
                this.localitaField = value;
                this.RaisePropertyChanged("localita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string localita2 {
            get {
                return this.localita2Field;
            }
            set {
                this.localita2Field = value;
                this.RaisePropertyChanged("localita2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://verifyWS.streetmaster/")]
    public partial class infoDetailVerify : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string civicoField;
        
        private int codComuneField;
        
        private int codStradaField;
        
        private string comuneMultiCapField;
        
        private string dugField;
        
        private string provEstesaField;
        
        private string regioneField;
        
        private string stradaMultiCapField;
        
        private string toponimoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string civico {
            get {
                return this.civicoField;
            }
            set {
                this.civicoField = value;
                this.RaisePropertyChanged("civico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codComune {
            get {
                return this.codComuneField;
            }
            set {
                this.codComuneField = value;
                this.RaisePropertyChanged("codComune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codStrada {
            get {
                return this.codStradaField;
            }
            set {
                this.codStradaField = value;
                this.RaisePropertyChanged("codStrada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string comuneMultiCap {
            get {
                return this.comuneMultiCapField;
            }
            set {
                this.comuneMultiCapField = value;
                this.RaisePropertyChanged("comuneMultiCap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dug {
            get {
                return this.dugField;
            }
            set {
                this.dugField = value;
                this.RaisePropertyChanged("dug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string provEstesa {
            get {
                return this.provEstesaField;
            }
            set {
                this.provEstesaField = value;
                this.RaisePropertyChanged("provEstesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string regione {
            get {
                return this.regioneField;
            }
            set {
                this.regioneField = value;
                this.RaisePropertyChanged("regione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string stradaMultiCap {
            get {
                return this.stradaMultiCapField;
            }
            set {
                this.stradaMultiCapField = value;
                this.RaisePropertyChanged("stradaMultiCap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string toponimo {
            get {
                return this.toponimoField;
            }
            set {
                this.toponimoField = value;
                this.RaisePropertyChanged("toponimo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://verifyWS.streetmaster/")]
    public partial class infoAlter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int capField;
        
        private int comuneField;
        
        private int dugField;
        
        private int frazioneField;
        
        private int provinciaField;
        
        private int viaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
                this.RaisePropertyChanged("comune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int dug {
            get {
                return this.dugField;
            }
            set {
                this.dugField = value;
                this.RaisePropertyChanged("dug");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int frazione {
            get {
                return this.frazioneField;
            }
            set {
                this.frazioneField = value;
                this.RaisePropertyChanged("frazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
                this.RaisePropertyChanged("via");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://verifyWS.streetmaster/")]
    public partial class outVerify : object, System.ComponentModel.INotifyPropertyChanged {
        
        private infoAlter alterField;
        
        private string capField;
        
        private string comuneField;
        
        private infoDetailVerify detailField;
        
        private string frazioneField;
        
        private string indirizzoField;
        
        private string provinciaField;
        
        private int scoreComuneField;
        
        private int scoreStradaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public infoAlter alter {
            get {
                return this.alterField;
            }
            set {
                this.alterField = value;
                this.RaisePropertyChanged("alter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cap {
            get {
                return this.capField;
            }
            set {
                this.capField = value;
                this.RaisePropertyChanged("cap");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string comune {
            get {
                return this.comuneField;
            }
            set {
                this.comuneField = value;
                this.RaisePropertyChanged("comune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public infoDetailVerify detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string frazione {
            get {
                return this.frazioneField;
            }
            set {
                this.frazioneField = value;
                this.RaisePropertyChanged("frazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string indirizzo {
            get {
                return this.indirizzoField;
            }
            set {
                this.indirizzoField = value;
                this.RaisePropertyChanged("indirizzo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int scoreComune {
            get {
                return this.scoreComuneField;
            }
            set {
                this.scoreComuneField = value;
                this.RaisePropertyChanged("scoreComune");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int scoreStrada {
            get {
                return this.scoreStradaField;
            }
            set {
                this.scoreStradaField = value;
                this.RaisePropertyChanged("scoreStrada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://verifyWS.streetmaster/")]
    public partial class totOutVerify : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codErrField;
        
        private int normField;
        
        private int numCandField;
        
        private outVerify[] outItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codErr {
            get {
                return this.codErrField;
            }
            set {
                this.codErrField = value;
                this.RaisePropertyChanged("codErr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int norm {
            get {
                return this.normField;
            }
            set {
                this.normField = value;
                this.RaisePropertyChanged("norm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numCand {
            get {
                return this.numCandField;
            }
            set {
                this.numCandField = value;
                this.RaisePropertyChanged("numCand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public outVerify[] outItem {
            get {
                return this.outItemField;
            }
            set {
                this.outItemField = value;
                this.RaisePropertyChanged("outItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Verify", WrapperNamespace="http://verifyWS.streetmaster/", IsWrapped=true)]
    public partial class VerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://verifyWS.streetmaster/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Verify_NET.VerifyWS.inputCommon inVerify;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://verifyWS.streetmaster/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        public VerifyRequest() {
        }
        
        public VerifyRequest(Verify_NET.VerifyWS.inputCommon inVerify, string key) {
            this.inVerify = inVerify;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyResponse", WrapperNamespace="http://verifyWS.streetmaster/", IsWrapped=true)]
    public partial class VerifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://verifyWS.streetmaster/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Verify_NET.VerifyWS.totOutVerify TotOutVerify;
        
        public VerifyResponse() {
        }
        
        public VerifyResponse(Verify_NET.VerifyWS.totOutVerify TotOutVerify) {
            this.TotOutVerify = TotOutVerify;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VerifyChannel : Verify_NET.VerifyWS.Verify, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerifyClient : System.ServiceModel.ClientBase<Verify_NET.VerifyWS.Verify>, Verify_NET.VerifyWS.Verify {
        
        public VerifyClient() {
        }
        
        public VerifyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerifyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Verify_NET.VerifyWS.VerifyResponse Verify_NET.VerifyWS.Verify.Verify(Verify_NET.VerifyWS.VerifyRequest request) {
            return base.Channel.Verify(request);
        }
        
        public Verify_NET.VerifyWS.totOutVerify Verify(Verify_NET.VerifyWS.inputCommon inVerify, string key) {
            Verify_NET.VerifyWS.VerifyRequest inValue = new Verify_NET.VerifyWS.VerifyRequest();
            inValue.inVerify = inVerify;
            inValue.key = key;
            Verify_NET.VerifyWS.VerifyResponse retVal = ((Verify_NET.VerifyWS.Verify)(this)).Verify(inValue);
            return retVal.TotOutVerify;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Verify_NET.VerifyWS.VerifyResponse> Verify_NET.VerifyWS.Verify.VerifyAsync(Verify_NET.VerifyWS.VerifyRequest request) {
            return base.Channel.VerifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Verify_NET.VerifyWS.VerifyResponse> VerifyAsync(Verify_NET.VerifyWS.inputCommon inVerify, string key) {
            Verify_NET.VerifyWS.VerifyRequest inValue = new Verify_NET.VerifyWS.VerifyRequest();
            inValue.inVerify = inVerify;
            inValue.key = key;
            return ((Verify_NET.VerifyWS.Verify)(this)).VerifyAsync(inValue);
        }
    }
}
